### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by matteomanzo** [sbardian/gatsby-plugin-breadcrumb#15]
Hello, I am using the "Sitemap Mode". I've included the gatsby-plugin-sitemap, generated the sitemap and it creates it correctly, but when I include this part in the plugins
``` 
{
  resolve: `gatsby-plugin-breadcrumb`,
  options: {
    sitemapPath: `/my-site-map.xml`,
  },
}
```
and run the app, I get:
```
ReferenceError: URL is not defined
- gatsby-node.js:38
  [project-name]/[gatsby-plugin-breadcrumb]/gatsby-node.js:38:15
```

Thanks

**Comment by eppemela** [comment]
Same here...

**Comment by sbardian** [comment]
Do you also have the plugin `gatsby-plugin-remove-trailing-slashes` ?  Just a thought off the top of my head.  I can do more testing on my end later today as well.

**Comment by sbardian** [comment]
Also, be sure to check out the Gotchas section if you missed it? 

https://github.com/sbardian/gatsby-plugin-breadcrumb#gotchas

**Comment by matteomanzo** [comment]
@sbardian yes I have got `gatsby-plugin-remove-trailing-slashes` installed and I made sure that my config respects the gotchas you mentioned, unfortunately this error keeps occurring.

**Comment by sbardian** [comment]
Thanks @matteomanzo. I'll do more troubleshooting on my end and see if I can reproduce.

**Comment by matteomanzo** [comment]
Thank you very much @sbardian

**Comment by sbardian** [comment]
I had a friend run through the Sitemap docs.  Seems I need to update some of the docs as they made sense to me writing them, but he was confused on some of them.  I will do that soon.  Otherwise he was able to use them and it seemed to work fine for him.  

I think this might be because of your version of node.  I think URL was introduced in node version 10.  Which I didn't even think about.  Could try updating your node and see, or I can try running a lower version of node and test on my end tonight.  If this is the case I might need to use something else other than URL for this.  Let me know if you are able to bump your node version and test, otherwise I'll test tonight.

**Comment by sbardian** [comment]
I tried using sitemap with node v8.10.0 and I get the same error.  So, I think its a pretty good guess this is why you are seeing this.  I will look into alternative modules that are supported by earlier versions of node.  For now I would use something like `nvm` / `n` / etc. to `use` a 10+ version of node to compile when using sitemap.

**Comment by sbardian** [comment]
Let me know if this doesn't fix the issue for you guys!   Sorry for the troubles.

**Comment by matteomanzo** [comment]
It works now! Thanks a lot you've been very quick!
